<?php

add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_6572da8d057aa',
        'title' => 'Festival',
        'fields' => array(
            array(
                'key' => 'field_6572da8d9827e',
                'label' => 'Cartel',
                'name' => 'hero',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Adjunta el cartel del festival. Tamaño ideal 1200 píxeles de ancho con una proporción 16:9.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6572dac99827f',
                'label' => 'Logo',
                'name' => 'logo',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Adjunta la imagen del logo del festival en un formato pequeño (ejemplo: 250px de ancho por 150px de alto)',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6572dae798280',
                'label' => 'Descripción',
                'name' => 'description',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Escribe toda la información acerca del festival',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_6572db9b98281',
                'label' => 'Color primario',
                'name' => 'primary_color',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => 'Selecciona el color de los elementos destacados del festival',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'enable_opacity' => 0,
                'return_format' => 'string',
            ),
            array(
                'key' => 'field_6572dbe998282',
                'label' => 'Color secundario',
                'name' => 'secondary_color',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => 'Selecciona el color del fondo de la página festival',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'enable_opacity' => 0,
                'return_format' => 'string',
            ),
            array(
                'key' => 'field_6572dc0198283',
                'label' => 'Color de text',
                'name' => 'text_color',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => 'Selecciona el color de la fuente (texto)',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'enable_opacity' => 0,
                'return_format' => 'string',
            ),
            array(
                'key' => 'field_6572dc1e98284',
                'label' => 'Twitter',
                'name' => 'twitter',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Inserta el link a la página de twitter del festival',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6572dc3098285',
                'label' => 'Instagram',
                'name' => 'instagram',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Inserta el link a la página de instagram del festival',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6572dc3b98286',
                'label' => 'Facebook',
                'name' => 'facebook',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Inserta el link a la página de facebook del festival',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6572dc5098287',
                'label' => 'Youtube',
                'name' => 'youtube',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Inserta el link a la página de youtube del festival',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6572dc5b98288',
                'label' => 'Web',
                'name' => 'web',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Inserta la URL de la página del festival',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6572dc7098289',
                'label' => 'Correo electronico',
                'name' => 'email',
                'aria-label' => '',
                'type' => 'email',
                'instructions' => 'Inserta la dirección de correo electrónico del festival',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6572dc819828a',
                'label' => 'Dirección',
                'name' => 'address',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Escribe la dirección física de contacto del festival (ejemplo: Avenida Libertad, 34 08004 Barcelona, España))',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6572dc919828b',
                'label' => 'Logos colaboradores',
                'name' => 'partners_logos',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Selecciona o adjunta los logos de la entidades colaboradoras con el festival (tamaño pequeño, ejemplo: 250x150 px o inferior))',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6572ddba9828c',
                'label' => 'Logo impulsores',
                'name' => 'founders_logos',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => 'Selecciona o adjunta los logos de la entidades impulsoras con el festival (tamaño pequeño, ejemplo: 250x150 px o inferior))',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6572ddfa9828d',
                'label' => 'Programacion',
                'name' => 'programacion',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => 'Adjunta el archivo con la programación en formato .pdf',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'pdf,',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'fest',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
