<?php

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'film_group',
        'title' => 'Film',
        'fields' => array(
            array(
                'key' => 'filmfield_title',
                'label' => "Títol de la pel·lícula",
                'name' => 'titulo',
                'type' => 'text',
                'instructions' => "Escriviu el títol de la pel·lícula",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'filmfield_vimeo',
                'label' => "Vimeo ID",
                'name' => 'vimeo_id',
                'type' => 'text',
                'instructions' => "Escriviu l'ID de la pel·lícula a vimeo",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'filmfield_cartellcarroussel',
                'label' => 'Cartell carroussel',
                'name' => 'cartel_en_carrousels',
                'type' => 'image',
                'instructions' => 'Escull la primera imatge del carroussel',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => 2000,
                'max_height' => 2000,
                'max_size' => '',
                'mime_types' => 'jpg, jpeg, png, webp',
            ),
            array(
                'key' => 'filmfield_cartellfitxa',
                'label' => 'Cartell fitxa',
                'name' => 'cartel_en_ficha',
                'type' => 'image',
                'instructions' => 'Escull la imatge del cartell que apareixerà a la fitxa',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => 2000,
                'max_height' => 2000,
                'max_size' => '',
                'mime_types' => 'jpg, jpeg, png, webp',
            ),
            array(
                'key' => 'filmfield_sinopsis',
                'label' => 'Sinopsis pel·lícula',
                'name' => 'sinopsis',
                'type' => 'wysiwyg',
                'instructions' => 'Escriu aquí la sinopsis de la pel·lícula',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'filmfield_sinopsisllarga',
                'label' => 'Sinopsis llarga pel·lícula',
                'name' => 'sinopsis_larga',
                'type' => 'wysiwyg',
                'instructions' => 'Escriu aquí la sinopsis llarga de la pel·lícula',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'filmfield_duracio',
                'label' => "Duració",
                'name' => 'duracion',
                'type' => 'text',
                'instructions' => "Especifiqueu la duració de la pel·lícula",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'filmfield_any',
                'label' => "Any",
                'name' => 'ano_produccion',
                'type' => 'text',
                'instructions' => "Especifiqueu l'any de la pel·lícula",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',

            ),
            array(
                'key' => 'filmfield_idioma',
                'label' => "Idioma",
                'name' => 'idioma',
                'type' => 'text',
                'instructions' => "Especifiqueu l'idioma de la pel·lícula",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',

            ),
            array(
                'key' => 'filmfield_metraje',
                'label' => "Metratge",
                'name' => 'metraje_pelicula',
                'type' => 'taxonomy',
                'instructions' => "Especifiqueu el tipus de metratge",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'mn_metraje',
                'field_type' => 'select',
                'allow_null' => 0,
                'multiple' => 0,
                'load_save_terms' => 0,
                'return_format' => 'object',
                'add_term' => 1,
                'ajax' => 0,
                'placeholder' => '',

            ),
            array(
                'key' => 'filmfield_subtitols',
                'label' => "Subtítols",
                'name' => 'subtitulos',
                'type' => 'text',
                'instructions' => "Especifiqueu l'idioma dels subtítols de la pel·lícula",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',

            ),
            array(
                'key' => 'filmfield_reparto',
                'label' => "Reparto",
                'name' => 'reparto',
                'type' => 'text',
                'instructions' => "Reparto",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'filmfield_premis',
                'label' => "Premis",
                'name' => 'premios',
                'type' => 'text',
                'instructions' => "Premis",
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'filmfield_enllaç',
                'label' => "Enllaç d'interés",
                'name' => 'enlaces',
                'type' => 'url',
                'instructions' => "Utilitzeu aquest camp per indicar on trobar més informació d'interés",
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'film',
                ),
            ),

        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        //'description' => 'Dates de l\'esdeveniment',
        'show_in_rest' => 1,
    ));

endif;
